### ISSUE TITLE
Errors Experienced During Install on CentOS 7

### ISSUE THREAD

**Issue by aokello** [tmobile/pacbot#44]
# ❔ Question

**Does anyone know how to resolve the issue below and can help me?** 

## 🔦 Context

_Currently, I'm attempting to install pacbot but it currently fails during the install and quits.  It states that "rule-engine.jar" is not available. I've attached both the printed return statement as well as the error components of the log file._

**The printed error statement returned:**

```
WARNING:python_terraform:error:
Error: Error applying plan:

1 error(s) occurred:

* null_resource.load_mysql_schema: Error running command 'mysql -u pacmanuser -ppacman123 -h pacmandbinstance.cqwfxlgk2owe.us-west-2.rds.amazonaws.com < DB_With_Values.sql': exit status 1. Output: ERROR 1064 (42000) at line 846: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO cf_AssetGroupDetails (groupId,groupName,dataSource,displayName,group' at line 5


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



oss-api  creation completed
Creating  lambda-submit
WARNING:python_terraform:error:
lambda-submit  creation completed
Execution started...............

Cloning the repository...............

Cloned repository to path: /tmp/pacman_cloned_dir_1541619661.6

Uploading Email templates to S3...............

Email templates upload to S3 completed...............

Started building the jar...............

Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/centos/pacbot/installer/awsterraformbuild.py", line 27, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/home/centos/pacbot/installer/jsonRead.py", line 596, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/home/centos/pacbot/installer/ui/build_apps.py", line 38, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code(cloned_repo)
  File "/home/centos/pacbot/installer/ui/build_apps.py", line 101, in build_jar_and_ui_from_code
    self.copy_jars_to_upload_dir(working_dir)
  File "/home/centos/pacbot/installer/ui/build_apps.py", line 129, in copy_jars_to_upload_dir
    shutil.copy2(copy_file_from, self.upload_dir)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/pacman_cloned_dir_1541619661.6/dist/jobs/rule-engine.jar'

```

**The contents of pacman-install.log are below:**

_[INFO] Building jar: /tmp/pacman_cloned_dir_1541619661.6/jobs/pacman-rule-engine-2.0/target/rule-engine.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] api-commons ....................................... SUCCESS [25.295s]
[INFO] commons ........................................... SUCCESS [5.738s]
[INFO] PacMan Commons Projects ........................... SUCCESS [0.003s]
[INFO] admin-service ..................................... SUCCESS [31.389s]
[INFO] asset-service ..................................... SUCCESS [41.810s]
[INFO] config ............................................ SUCCESS [10.981s]
[INFO] compliance-service ................................ SUCCESS [15.418s]
[INFO] notification-service .............................. SUCCESS [7.346s]
[INFO] statistics-service ................................ SUCCESS [4.544s]
[INFO] auth-service ...................................... SUCCESS [5.614s]
[INFO] PacMan Api Projects ............................... SUCCESS [0.615s]
[INFO] inventoryFetch .................................... SUCCESS [1:19.782s]
[INFO] data-shipper ...................................... SUCCESS [7.865s]
[INFO] awsrules .......................................... SUCCESS [20.870s]
[INFO] pacman-rule-engine ................................ FAILURE [31.102s]
[INFO] PacMan Jobs Projects .............................. SKIPPED
[INFO] PacBot UI ......................................... SKIPPED
[INFO] PacMan ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:59.194s
[INFO] Finished at: Wed Nov 07 19:46:14 UTC 2018
Cleaning up unclosed ZipFile for archive /root/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[INFO] Final Memory: 237M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (build-a) on project rule-engine: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Problem creating jar: Execution exception: Java heap space -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rule-engine
-es-data-shipper"
  target_id: "" => "pacman-submitBatchjob"
aws_lambda_permission.lambda_invoke2: Creating...
  action:        "" => "lambda:InvokeFunction"
  function_name: "" => "pacman-submitBatchjob"
  principal:     "" => "events.amazonaws.com"
  source_arn:    "" => "arn:aws:events:us-west-2:245459132561:rule/aws-redshift-es-data-shipper"
  statement_id:  "" => "AllowExecutionFromCloudWatch2"
aws_lambda_permission.lambda_invoke1: Creation complete after 0s (ID: AllowExecutionFromCloudWatch1)
aws_cloudwatch_event_target.target_for_cloudwatch: Creation complete after 0s (ID: AWS-Data-Collector-pacman-submitBatchjob)
aws_cloudwatch_event_target.pacman_redshift_for_cloudwatch: Creation complete after 0s (ID: aws-redshift-es-data-shipper-pacman-submitBatchjob)
aws_lambda_permission.lambda_invoke2: Creation complete after 0s (ID: AllowExecutionFromCloudWatch2)

Apply complete! Resources: 7 added, 0 changed, 0 destroyed._

**Comment by bobrich** [comment]
Two things.

```
* null_resource.load_mysql_schema: Error running command 'mysql -u pacmanuser -ppacman123 -h pacmandbinstance.cqwfxlgk2owe.us-west-2.rds.amazonaws.com < DB_With_Values.sql': exit status 1. Output: ERROR 1064 (42000) at line 846: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO cf_AssetGroupDetails (groupId,groupName,dataSource,displayName,group' at line 5
```

The mysql error can be fixed by adding a semicolon at the end of line 846 in the DB.sql file.  See https://github.com/tmobile/pacbot/issues/41

```
Problem creating jar: Execution exception: Java heap space -> [Help 1]
```

The build error appears to be a heap space issue with Maven.  I did a google and found that setting the following before the build may help:

export MAVEN_OPTS="-Xmx1G"

Of course ensure that the host you're building on can spare the change.

**Comment by johnakash** [comment]
@bobrich , thanks for the suggestions and are correct. 

@aokello 
SQL syntax error is fixed and merged to master branch now

Related to build failure, we are assuming you are trying to install PacBot from /root directory. Could you please change the directory to /opt or any other location and give a try?  Please make sure you are cleaned all the PacBot related resources from your aws account before re-running the installer.

**Comment by aokello** [comment]
Thanks Bob, I'm still receiving this error: IOError: [Errno 2] No such file or directory: '/tmp/pacman_cloned_dir_1541804101.93/dist/jobs/rule-engine.jar'

How do I make sure the file and/or directory is being made?

I've included the full message below as well.
  ```Uploading Email templates to S3...............

Email templates upload to S3 completed...............

Started building the jar...............

Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/centos/pacbot/installer/awsterraformbuild.py", line 27, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/home/centos/pacbot/installer/jsonRead.py", line 596, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/home/centos/pacbot/installer/ui/build_apps.py", line 38, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code(cloned_repo)
  File "/home/centos/pacbot/installer/ui/build_apps.py", line 101, in build_jar_and_ui_from_code
    self.copy_jars_to_upload_dir(working_dir)
  File "/home/centos/pacbot/installer/ui/build_apps.py", line 129, in copy_jars_to_upload_dir
    shutil.copy2(copy_file_from, self.upload_dir)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/pacman_cloned_dir_1541804101.93/dist/jobs/rule-engine.jar'

```

**Comment by johnakash** [comment]
Clone the pacbot to another directory (/opt/) and start installation from there.

**Comment by aokello** [comment]
Hi @johnakash & @bobrich,

I'd tried the install again (in the /opt/ folder) but this time on an Amazon Linux 2 instance and received the same error of: 
`Started building the jar...............

Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/opt/pacbot/installer/awsterraformbuild.py", line 27, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/opt/pacbot/installer/jsonRead.py", line 596, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/opt/pacbot/installer/ui/build_apps.py", line 38, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code(cloned_repo)
  File "/opt/pacbot/installer/ui/build_apps.py", line 101, in build_jar_and_ui_from_code
    self.copy_jars_to_upload_dir(working_dir)
  File "/opt/pacbot/installer/ui/build_apps.py", line 129, in copy_jars_to_upload_dir
    shutil.copy2(copy_file_from, self.upload_dir)
  File "/usr/lib64/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/pacman_cloned_dir_1542135237.04/dist/jobs/rule-engine.jar'
[ec2-user@ip-10-0-0-169 installer]$ 
`

What component ensure's that there's the rule-engine.jar in the directory?

**Comment by gabel0287** [comment]
I think this is your issue https://github.com/tmobile/pacbot/pull/40

**Comment by sachin6128** [comment]
Hello @gabel0287, I faced such similar issues in the past and the best option to get rid of those is as follows:
1. Destroy your pacbot setup
2. Ensure all the resources are removed. For e.g. as of now the destroy do not remove keypair, s3 bucket, CloudWatch logs and IAM roles/policies
3. Terminate the instance from which you were running the setup. I hope the instance was just created just for launching Pacbot.
4. Start a new CentOS instance (AMI ami-dd3c0f36 works pretty well in Frankfurt) but a similar one for your region should work fine
5. Download Pacbot and Start your setup again.

It took a while for me to get Pacbot properly installed. Initially I too tried it installing it from a different location within the same instance but everytime it failed.

**Comment by aokello** [comment]
Hi @sachin6128,

I tried the install following your suggestions and receive the same error. I've also created a different instance to test building simply the rule-engine.jar and came across this error: **_"Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT"_** The full debug is copied below for your reference. How should I add the batch-commons dependency to the pom file?

`[centos@ip-10-0-0-139 pacman-rule-engine-2.0]$ mvn package -U -X
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.3.2.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/centos/.m2/settings.xml
[DEBUG] Using local repository at /home/centos/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/centos/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.tmobile.cloud:rule-engine:jar:1.0.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.tmobile.cloud:rule-engine:jar:1.0.0-SNAPSHOT
[DEBUG] Tasks:   [package]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pacman-rule-engine 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.tmobile.cloud:rule-engine:1.0.0-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [compile, runtime, test]
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.jacoco:jacoco-maven-plugin:0.7.9:prepare-agent (default)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <address>${jacoco.address}</address>
  <append>${jacoco.append}</append>
  <classDumpDir>${jacoco.classDumpDir}</classDumpDir>
  <destFile default-value="${project.build.directory}/jacoco.exec">${jacoco.destFile}</destFile>
  <dumpOnExit>${jacoco.dumpOnExit}</dumpOnExit>
  <exclClassLoaders>${jacoco.exclClassLoaders}</exclClassLoaders>
  <inclBootstrapClasses>${jacoco.inclBootstrapClasses}</inclBootstrapClasses>
  <inclNoLocationClasses>${jacoco.inclNoLocationClasses}</inclNoLocationClasses>
  <jmx>${jacoco.jmx}</jmx>
  <output>${jacoco.output}</output>
  <pluginArtifactMap>${plugin.artifactMap}</pluginArtifactMap>
  <port>${jacoco.port}</port>
  <project>${project}</project>
  <propertyName>${jacoco.propertyName}</propertyName>
  <sessionId>${jacoco.sessionId}</sessionId>
  <skip default-value="false">${jacoco.skip}</skip>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <buildFilters default-value="${project.build.filters}"/>
  <delimiters>
    <delimiter>@</delimiter>
  </delimiters>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <escapeString>${maven.resources.escapeString}</escapeString>
  <escapeWindowsPaths default-value="true">${maven.resources.escapeWindowsPaths}</escapeWindowsPaths>
  <includeEmptyDirs default-value="false">${maven.resources.includeEmptyDirs}</includeEmptyDirs>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <overwrite default-value="false">${maven.resources.overwrite}</overwrite>
  <project default-value="${project}"/>
  <resources default-value="${project.resources}"/>
  <session default-value="${session}"/>
  <supportMultiLineFiltering default-value="false">${maven.resources.supportMultiLineFiltering}</supportMultiLineFiltering>
  <useBuildFilters default-value="true"/>
  <useDefaultDelimiters default-value="true">false</useDefaultDelimiters>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <basedir default-value="${basedir}"/>
  <buildDirectory default-value="${project.build.directory}"/>
  <classpathElements default-value="${project.compileClasspathElements}"/>
  <compileSourceRoots default-value="${project.compileSourceRoots}"/>
  <compilerId default-value="javac">${maven.compiler.compilerId}</compilerId>
  <compilerReuseStrategy default-value="${reuseCreated}">${maven.compiler.compilerReuseStrategy}</compilerReuseStrategy>
  <compilerVersion>${maven.compiler.compilerVersion}</compilerVersion>
  <debug default-value="true">${maven.compiler.debug}</debug>
  <debuglevel>${maven.compiler.debuglevel}</debuglevel>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <executable>${maven.compiler.executable}</executable>
  <failOnError default-value="true">${maven.compiler.failOnError}</failOnError>
  <forceJavacCompilerUse default-value="false">${maven.compiler.forceJavacCompilerUse}</forceJavacCompilerUse>
  <fork default-value="false">${maven.compiler.fork}</fork>
  <generatedSourcesDirectory default-value="${project.build.directory}/generated-sources/annotations"/>
  <maxmem>${maven.compiler.maxmem}</maxmem>
  <meminitial>${maven.compiler.meminitial}</meminitial>
  <mojoExecution>${mojoExecution}</mojoExecution>
  <optimize default-value="false">${maven.compiler.optimize}</optimize>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <projectArtifact default-value="${project.artifact}"/>
  <showDeprecation default-value="false">${maven.compiler.showDeprecation}</showDeprecation>
  <showWarnings default-value="false">${maven.compiler.showWarnings}</showWarnings>
  <skipMain>${maven.main.skip}</skipMain>
  <skipMultiThreadWarning default-value="false">${maven.compiler.skipMultiThreadWarning}</skipMultiThreadWarning>
  <source default-value="1.5">${maven.compiler.source}</source>
  <staleMillis default-value="0">${lastModGranularityMs}</staleMillis>
  <target default-value="1.5">${maven.compiler.target}</target>
  <useIncrementalCompilation default-value="true">${maven.compiler.useIncrementalCompilation}</useIncrementalCompilation>
  <verbose default-value="false">${maven.compiler.verbose}</verbose>
  <mavenSession default-value="${session}"/>
  <session default-value="${session}"/>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-resources-plugin:2.6:testResources (default-testResources)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <buildFilters default-value="${project.build.filters}"/>
  <delimiters>
    <delimiter>@</delimiter>
  </delimiters>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <escapeString>${maven.resources.escapeString}</escapeString>
  <escapeWindowsPaths default-value="true">${maven.resources.escapeWindowsPaths}</escapeWindowsPaths>
  <includeEmptyDirs default-value="false">${maven.resources.includeEmptyDirs}</includeEmptyDirs>
  <outputDirectory default-value="${project.build.testOutputDirectory}"/>
  <overwrite default-value="false">${maven.resources.overwrite}</overwrite>
  <project default-value="${project}"/>
  <resources default-value="${project.testResources}"/>
  <session default-value="${session}"/>
  <skip>${maven.test.skip}</skip>
  <supportMultiLineFiltering default-value="false">${maven.resources.supportMultiLineFiltering}</supportMultiLineFiltering>
  <useBuildFilters default-value="true"/>
  <useDefaultDelimiters default-value="true">false</useDefaultDelimiters>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <basedir default-value="${basedir}"/>
  <buildDirectory default-value="${project.build.directory}"/>
  <classpathElements default-value="${project.testClasspathElements}"/>
  <compileSourceRoots default-value="${project.testCompileSourceRoots}"/>
  <compilerId default-value="javac">${maven.compiler.compilerId}</compilerId>
  <compilerReuseStrategy default-value="${reuseCreated}">${maven.compiler.compilerReuseStrategy}</compilerReuseStrategy>
  <compilerVersion>${maven.compiler.compilerVersion}</compilerVersion>
  <debug default-value="true">${maven.compiler.debug}</debug>
  <debuglevel>${maven.compiler.debuglevel}</debuglevel>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <executable>${maven.compiler.executable}</executable>
  <failOnError default-value="true">${maven.compiler.failOnError}</failOnError>
  <forceJavacCompilerUse default-value="false">${maven.compiler.forceJavacCompilerUse}</forceJavacCompilerUse>
  <fork default-value="false">${maven.compiler.fork}</fork>
  <generatedTestSourcesDirectory default-value="${project.build.directory}/generated-test-sources/test-annotations"/>
  <maxmem>${maven.compiler.maxmem}</maxmem>
  <meminitial>${maven.compiler.meminitial}</meminitial>
  <mojoExecution>${mojoExecution}</mojoExecution>
  <optimize default-value="false">${maven.compiler.optimize}</optimize>
  <outputDirectory default-value="${project.build.testOutputDirectory}"/>
  <showDeprecation default-value="false">${maven.compiler.showDeprecation}</showDeprecation>
  <showWarnings default-value="false">${maven.compiler.showWarnings}</showWarnings>
  <skip>${maven.test.skip}</skip>
  <skipMultiThreadWarning default-value="false">${maven.compiler.skipMultiThreadWarning}</skipMultiThreadWarning>
  <source default-value="1.5">${maven.compiler.source}</source>
  <staleMillis default-value="0">${lastModGranularityMs}</staleMillis>
  <target default-value="1.5">${maven.compiler.target}</target>
  <testSource>${maven.compiler.testSource}</testSource>
  <testTarget>${maven.compiler.testTarget}</testTarget>
  <useIncrementalCompilation default-value="true">${maven.compiler.useIncrementalCompilation}</useIncrementalCompilation>
  <verbose default-value="false">${maven.compiler.verbose}</verbose>
  <mavenSession default-value="${session}"/>
  <session default-value="${session}"/>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <additionalClasspathElements>${maven.test.additionalClasspath}</additionalClasspathElements>
  <argLine>${argLine}</argLine>
  <basedir default-value="${basedir}"/>
  <childDelegation default-value="false">${childDelegation}</childDelegation>
  <classesDirectory default-value="${project.build.outputDirectory}"/>
  <classpathDependencyExcludes>${maven.test.dependency.excludes}</classpathDependencyExcludes>
  <debugForkedProcess>${maven.surefire.debug}</debugForkedProcess>
  <dependenciesToScan>${dependenciesToScan}</dependenciesToScan>
  <disableXmlReport default-value="false">${disableXmlReport}</disableXmlReport>
  <enableAssertions default-value="true">${enableAssertions}</enableAssertions>
  <excludedGroups>${excludedGroups}</excludedGroups>
  <excludes>
    <exclude>**/Abstract*.java</exclude>
  </excludes>
  <failIfNoSpecifiedTests>${surefire.failIfNoSpecifiedTests}</failIfNoSpecifiedTests>
  <failIfNoTests>${failIfNoTests}</failIfNoTests>
  <forkCount default-value="1">${forkCount}</forkCount>
  <forkMode default-value="once">${forkMode}</forkMode>
  <forkedProcessTimeoutInSeconds>${surefire.timeout}</forkedProcessTimeoutInSeconds>
  <groups>${groups}</groups>
  <includes>
    <include>**/*Tests.java</include>
    <include>**/*Test.java</include>
  </includes>
  <junitArtifactName default-value="junit:junit">${junitArtifactName}</junitArtifactName>
  <jvm>${jvm}</jvm>
  <localRepository default-value="${localRepository}"/>
  <objectFactory>${objectFactory}</objectFactory>
  <parallel>${parallel}</parallel>
  <parallelMavenExecution default-value="${session.parallel}"/>
  <parallelOptimized default-value="true">${parallelOptimized}</parallelOptimized>
  <parallelTestsTimeoutForcedInSeconds>${surefire.parallel.forcedTimeout}</parallelTestsTimeoutForcedInSeconds>
  <parallelTestsTimeoutInSeconds>${surefire.parallel.timeout}</parallelTestsTimeoutInSeconds>
  <perCoreThreadCount default-value="true">${perCoreThreadCount}</perCoreThreadCount>
  <pluginArtifactMap>${plugin.artifactMap}</pluginArtifactMap>
  <pluginDescriptor default-value="${plugin}"/>
  <printSummary default-value="true">${surefire.printSummary}</printSummary>
  <projectArtifactMap>${project.artifactMap}</projectArtifactMap>
  <redirectTestOutputToFile default-value="false">${maven.test.redirectTestOutputToFile}</redirectTestOutputToFile>
  <remoteRepositories default-value="${project.pluginArtifactRepositories}"/>
  <reportFormat default-value="brief">${surefire.reportFormat}</reportFormat>
  <reportNameSuffix default-value="">${surefire.reportNameSuffix}</reportNameSuffix>
  <reportsDirectory default-value="${project.build.directory}/surefire-reports"/>
  <rerunFailingTestsCount default-value="0">${surefire.rerunFailingTestsCount}</rerunFailingTestsCount>
  <reuseForks default-value="true">${reuseForks}</reuseForks>
  <runOrder default-value="filesystem">${surefire.runOrder}</runOrder>
  <skip default-value="false">${maven.test.skip}</skip>
  <skipExec>${maven.test.skip.exec}</skipExec>
  <skipTests default-value="false">${skipTests}</skipTests>
  <suiteXmlFiles>${surefire.suiteXmlFiles}</suiteXmlFiles>
  <test>${test}</test>
  <testClassesDirectory default-value="${project.build.testOutputDirectory}"/>
  <testFailureIgnore default-value="false">${maven.test.failure.ignore}</testFailureIgnore>
  <testNGArtifactName default-value="org.testng:testng">${testNGArtifactName}</testNGArtifactName>
  <testSourceDirectory default-value="${project.build.testSourceDirectory}"/>
  <threadCount>${threadCount}</threadCount>
  <threadCountClasses default-value="0">${threadCountClasses}</threadCountClasses>
  <threadCountMethods default-value="0">${threadCountMethods}</threadCountMethods>
  <threadCountSuites default-value="0">${threadCountSuites}</threadCountSuites>
  <trimStackTrace default-value="true">${trimStackTrace}</trimStackTrace>
  <useFile default-value="true">${surefire.useFile}</useFile>
  <useManifestOnlyJar default-value="true">${surefire.useManifestOnlyJar}</useManifestOnlyJar>
  <useSystemClassLoader default-value="true">${surefire.useSystemClassLoader}</useSystemClassLoader>
  <useUnlimitedThreads default-value="false">${useUnlimitedThreads}</useUnlimitedThreads>
  <workingDirectory>${basedir}</workingDirectory>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-jar-plugin:2.6:jar (default-jar)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <archive>
    <manifest>
      <mainClass>${start-class}</mainClass>
      <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
    </manifest>
  </archive>
  <classesDirectory default-value="${project.build.outputDirectory}"/>
  <classifier default-value="">${maven.jar.classifier}</classifier>
  <defaultManifestFile default-value="${project.build.outputDirectory}/META-INF/MANIFEST.MF"/>
  <finalName default-value="${project.build.finalName}">${jar.finalName}</finalName>
  <forceCreation default-value="false">${jar.forceCreation}</forceCreation>
  <outputDirectory default-value="${project.build.directory}"/>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
  <skipIfEmpty default-value="false">${jar.skipIfEmpty}</skipIfEmpty>
  <useDefaultManifestFile default-value="false">${jar.useDefaultManifestFile}</useDefaultManifestFile>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-assembly-plugin:2.6:single (build-a)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appendAssemblyId default-value="true">false</appendAssemblyId>
  <archive></archive>
  <attach default-value="true">${assembly.attach}</attach>
  <basedir default-value="${project.basedir}"/>
  <classifier>${classifier}</classifier>
  <descriptor>${descriptor}</descriptor>
  <descriptorId>${descriptorId}</descriptorId>
  <descriptorRefs>
    <descriptorRef>jar-with-dependencies</descriptorRef>
  </descriptorRefs>
  <dryRun default-value="false">${assembly.dryRun}</dryRun>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <escapeString>${assembly.escapeString}</escapeString>
  <finalName default-value="${project.build.finalName}">rule-engine</finalName>
  <ignoreDirFormatExtensions default-value="true"/>
  <ignoreMissingDescriptor default-value="false">${assembly.ignoreMissingDescriptor}</ignoreMissingDescriptor>
  <ignorePermissions default-value="false">${assembly.ignorePermissions}</ignorePermissions>
  <includeProjectBuildFilters default-value="true">${assembly.includeProjectBuildFilters}</includeProjectBuildFilters>
  <includeSite default-value="false">${includeSite}</includeSite>
  <localRepository default-value="${localRepository}"/>
  <mavenSession default-value="${session}"/>
  <outputDirectory default-value="${project.build.directory}"/>
  <project default-value="${project}"/>
  <reactorProjects default-value="${reactorProjects}"/>
  <recompressZippedFiles default-value="true">false</recompressZippedFiles>
  <remoteRepositories default-value="${project.remoteArtifactRepositories}"/>
  <runOnlyAtExecutionRoot default-value="false">${assembly.runOnlyAtExecutionRoot}</runOnlyAtExecutionRoot>
  <siteDirectory default-value="${project.reporting.outputDirectory}"/>
  <skipAssembly default-value="false">${assembly.skipAssembly}</skipAssembly>
  <tarLongFileMode default-value="warn">${assembly.tarLongFileMode}</tarLongFileMode>
  <tempRoot default-value="${project.build.directory}/archive-tmp"/>
  <updateOnly default-value="false">${assembly.updateOnly}</updateOnly>
  <useJvmChmod default-value="false">${assembly.useJvmChmod}</useJvmChmod>
  <workDirectory default-value="${project.build.directory}/assembly/work"/>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Could not find metadata com.tmobile.cloud:batch-commons:1.0.0-SNAPSHOT/maven-metadata.xml in local (/home/centos/.m2/repository)
[DEBUG] Could not find metadata com.tmobile.cloud:batch-commons:1.0.0-SNAPSHOT/maven-metadata.xml in local (/home/centos/.m2/repository)
[WARNING] The POM for com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[DEBUG] com.tmobile.cloud:rule-engine:jar:1.0.0-SNAPSHOT
[DEBUG]    org.apache.commons:commons-text:jar:1.1:compile
[DEBUG]       org.apache.commons:commons-lang3:jar:3.5:compile
[DEBUG]    org.elasticsearch:elasticsearch:jar:5.6.8:compile
[DEBUG]       org.apache.lucene:lucene-core:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-analyzers-common:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-backward-codecs:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-grouping:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-highlighter:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-join:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-memory:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-misc:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-queries:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-queryparser:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-sandbox:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-spatial:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-spatial-extras:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-spatial3d:jar:6.6.1:compile
[DEBUG]       org.apache.lucene:lucene-suggest:jar:6.6.1:compile
[DEBUG]       org.elasticsearch:securesm:jar:1.2:compile
[DEBUG]       net.sf.jopt-simple:jopt-simple:jar:5.0.2:compile
[DEBUG]       com.carrotsearch:hppc:jar:0.7.1:compile
[DEBUG]       joda-time:joda-time:jar:2.9.9:compile (version managed from 2.9.5 by org.springframework.boot:spring-boot-dependencies:1.5.6.RELEASE)
[DEBUG]       org.yaml:snakeyaml:jar:1.17:compile (version managed from 1.15 by org.springframework.boot:spring-boot-dependencies:1.5.6.RELEASE)
[DEBUG]       com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.8.9:compile (version managed from 2.8.6 by com.fasterxml.jackson:jackson-bom:2.8.9)
[DEBUG]       com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.9:compile (version managed from 2.8.6 by com.fasterxml.jackson:jackson-bom:2.8.9)
[DEBUG]       com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.8.9:compile (version managed from 2.8.6 by com.fasterxml.jackson:jackson-bom:2.8.9)
[DEBUG]       com.tdunning:t-digest:jar:3.0:compile
[DEBUG]       org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[DEBUG]       org.apache.logging.log4j:log4j-api:jar:2.7:compile (version managed from 2.9.1 by org.apache.logging.log4j:log4j-bom:2.7)
[DEBUG]       org.elasticsearch:jna:jar:4.4.0-1:compile
[DEBUG]    org.elasticsearch.client:elasticsearch-rest-high-level-client:jar:5.6.8:compile
[DEBUG]       org.elasticsearch.client:elasticsearch-rest-client:jar:5.6.8:compile
[DEBUG]          org.apache.httpcomponents:httpasyncclient:jar:4.1.3:compile (version managed from 4.1.2 by org.springframework.boot:spring-boot-dependencies:1.5.6.RELEASE)
[DEBUG]          org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
[DEBUG]       org.elasticsearch.plugin:parent-join-client:jar:5.6.8:compile
[DEBUG]          org.locationtech.spatial4j:spatial4j:jar:0.6:compile
[DEBUG]          com.vividsolutions:jts:jar:1.13:compile
[DEBUG]          org.apache.logging.log4j:log4j-core:jar:2.7:compile (version managed from 2.9.1 by org.apache.logging.log4j:log4j-bom:2.7)
[DEBUG]       org.elasticsearch.plugin:aggs-matrix-stats-client:jar:5.6.8:compile
[DEBUG]    com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT:compile
[DEBUG]    com.google.code.gson:gson:jar:2.8.1:compile
[DEBUG]    com.internetitem:logback-elasticsearch-appender:jar:1.6:compile
[DEBUG]    ch.qos.logback:logback-access:jar:1.2.3:compile
[DEBUG]    org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.25:compile
[DEBUG]    commons-httpclient:commons-httpclient:jar:3.1:compile
[DEBUG]       commons-logging:commons-logging:jar:1.0.4:compile
[DEBUG]       commons-codec:commons-codec:jar:1.10:compile (version managed from 1.2 by org.springframework.boot:spring-boot-dependencies:1.5.6.RELEASE)
[DEBUG]    junit:junit:jar:4.12:test
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.3:test
[DEBUG]    org.powermock:powermock-module-junit4:jar:1.6.4:test
[DEBUG]       org.powermock:powermock-module-junit4-common:jar:1.6.4:test
[DEBUG]          org.powermock:powermock-core:jar:1.6.4:test
[DEBUG]          org.powermock:powermock-reflect:jar:1.6.4:test
[DEBUG]    org.powermock:powermock-api-mockito:jar:1.6.4:test
[DEBUG]       org.mockito:mockito-core:jar:1.10.19:test
[DEBUG]          org.objenesis:objenesis:jar:2.1:test
[DEBUG]       org.powermock:powermock-api-support:jar:1.6.4:test
[DEBUG]    org.reflections:reflections:jar:0.9.10:compile
[DEBUG]       org.javassist:javassist:jar:3.21.0-GA:compile (version managed from 3.19.0-GA by org.springframework.boot:spring-boot-dependencies:1.5.6.RELEASE)
[DEBUG]       com.google.code.findbugs:annotations:jar:2.0.1:compile
[DEBUG]    com.google.guava:guava:jar:19.0:compile
[DEBUG]    ch.qos.logback:logback-classic:jar:1.2.3:compile
[DEBUG]    ch.qos.logback:logback-core:jar:1.2.3:compile
[DEBUG]    com.fasterxml.jackson.core:jackson-core:jar:2.8.5:compile
[DEBUG]    org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[DEBUG]       org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[DEBUG]    org.assertj:assertj-core:jar:3.8.0:test
[DEBUG]    org.thymeleaf:thymeleaf:jar:3.0.9.RELEASE:compile
[DEBUG]       ognl:ognl:jar:3.1.12:compile
[DEBUG]       org.attoparser:attoparser:jar:2.0.4.RELEASE:compile
[DEBUG]       org.unbescape:unbescape:jar:1.1.5.RELEASE:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.075s
[INFO] Finished at: Tue Nov 20 00:02:18 UTC 2018
[INFO] Final Memory: 14M/33M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project rule-engine: Could not resolve dependencies for project com.tmobile.cloud:rule-engine:jar:1.0.0-SNAPSHOT: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project rule-engine: Could not resolve dependencies for project com.tmobile.cloud:rule-engine:jar:1.0.0-SNAPSHOT: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.tmobile.cloud:rule-engine:jar:1.0.0-SNAPSHOT: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
	... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
	... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.tmobile.cloud:batch-commons:jar:1.0.0-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
	... 26 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

**Comment by johnakash** [comment]
@aokello We can have a screen-share session to help you. Please let us know your convenient time.

**Comment by johnakash** [comment]
Yes, sure. Let us know when you are available we can have a quick screenshare session.

**Comment by aokello** [comment]
Hi Akash,

I’m free now if you are? How shall we set up the screen share?

-A. Okello

**Comment by aokello** [comment]
If you’d like, I’ve set up this webex as well:

https://attcorp.webex.com/join/ma893k

-A. Okello


From: OKELLO, AARON M
Sent: Friday, December 07, 2018 10:59 AM
To: 'tmobile/pacbot' <reply@reply.github.com>; tmobile/pacbot <pacbot@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [tmobile/pacbot] Errors Experienced During Install on CentOS 7 (#44)

Hi Akash,

I’m free now if you are? How shall we set up the screen share?

-A. Okello

**Comment by johnakash** [comment]
We are ready to join. Please join in to https://t-mobile.webex.com/join/VVaradh

**Comment by johnakash** [comment]
@aokello , Thanks for working together and closing it out.

**Comment by pascalvon12** [comment]
Hello Team, I started installing PacBot on ubuntu 20.04 and getting this error "Checking user-attached policies ...................................................... [Not Present]"

I have tried all what i can but still getting the same error. Can someone please help me.

**Comment by pascalvon12** [comment]
@johnakash I started installing PacBot on ubuntu 20.04 and getting this error "Checking user-attached policies ...................................................... [Not Present]"

I have tried all what i can but still getting the same error. Can someone please help me.
